import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

import { Zen_Dots } from "next/font/google";
const zendots = Zen_Dots({
  weight: ["400"],
  display: "auto",
  subsets: ["latin"],
  variable: "--font-zendots",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>gym app</title>
      </head>
      <body className={`${zendots.variable}`}>{children}</body>
    </html>
  );
}
